blog/urls.py
from django.urls import path

from blog.views import blog, single

app_name = 'blog'

urlpatterns = [
    path('blog/', blog, name='blog'),
    path('single/', single, name='single'),

]

car_rent/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from car_rent import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import index, about, services, cars, contact

app_name = 'webapp'

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),
    path('services/', services, name='services'),
    path('cars/', cars, name='cars'),
    path('contact/', contact, name='contact'),

]

blog/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Car(models.Model):
    """car model"""
    TRANSMISSION_CHOISES = [
        ('automatic', 'Automatic'),
        ('manual', 'Manual'),
    ]
    title = models.CharField(max_length=100)
    door_num = models.PositiveIntegerField()
    seat_num = models.PositiveIntegerField()
    transmission = models.CharField(max_length=10, choices=TRANSMISSION_CHOISES)
    rating = models.PositiveIntegerField(validators=[
        MinValueValidator(0),
        MaxValueValidator(5),
    ])
    price = models.PositiveIntegerField()
    photo = models.IntegerField()#upload_to='car_photos/', blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render

def blog(request):
    return render(request, 'blog/blog.html')


def single(request):
    return render(request, 'blog/single.html')

webapp/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from webapp.models import Car

def index(request):
    return render(request, 'webapp/index.html')


def about(request):
    return render(request, 'webapp/about.html')


def services(request):
    return render(request, 'webapp/services.html')


def contact(request):
    return render(request, 'webapp/contact.html')


def cars(request):
    cars = Car.objects.all()
    paginator = Paginator(cars, 4)
    page_number = request.GET.get('page')

    context = {'cars': cars}
    return render(request, 'webapp/cars.html')

blog/templates/blog/blog.html
{% extends 'main/base.html' %}
{% load static %}


    {% block content %}

    <div class="ftco-blocks-cover-1">
      <div class="ftco-cover-1 overlay innerpage" style="background-image: url('../../static/blog/images/hero_2.jpg')">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-lg-6 text-center">
              <h1>Car Articles</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="{% url 'blog:single' %}">
                <img src="{% static 'blog/images/post_1.jpg' %}" alt="Image" class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="{% url 'blog:single' %}">The best car rent in the entire planet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="{% url 'blog:single' %}">
                <img src="{% static 'blog/images/img_2.jpg' %}" alt="Image" class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="{% url 'blog:single' %}">The best car rent in the entire planet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="{% url 'blog:single' %}">
                <img src="{% static 'blog/images/img_3.jpg' %}" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="{% url 'blog:single' %}">The best car rent in the entire planet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="{% url 'blog:single' %}">
                <img src="{% static 'webapp/images/post_1.jpg' %}" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="{% url 'blog:single' %}">The best car rent in the entire planet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="{% url 'blog:single' %}">
                <img src="{% static 'blog/images/img_2.jpg' %}" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="{% url 'blog:single' %}">The best car rent in the entire planet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="{% url 'blog:single' %}">
                <img src="{% static 'webapp/images/img_3.jpg' %}" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="{% url 'blog:single' %}">The best car rent in the entire planet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>

          <div class="col-12">
            <span class="p-3">1</span>
            <a href="#" class="p-3">2</a>
            <a href="#" class="p-3">3</a>
            <a href="#" class="p-3">4</a>
          </div>
        </div>
      </div>
    </div>

    <div class="container site-section mb-5">
      <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
          <h2>How it works</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius earum voluptates sed!</p>
        </div>
      </div>
      <div class="how-it-works d-flex">
        <div class="step">
          <span class="number"><span>01</span></span>
          <span class="caption">Time &amp; Place</span>
        </div>
        <div class="step">
          <span class="number"><span>02</span></span>
          <span class="caption">Car</span>
        </div>
        <div class="step">
          <span class="number"><span>03</span></span>
          <span class="caption">Details</span>
        </div>
        <div class="step">
          <span class="number"><span>04</span></span>
          <span class="caption">Checkout</span>
        </div>
        <div class="step">
          <span class="number"><span>05</span></span>
          <span class="caption">Done</span>
        </div>

      </div>
    </div>

    {% endblock %}

templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <title>Car Rent &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href= "{% static 'webapp/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href= "{% static 'webapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/aos.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href= "{% static 'webapp/css/style.css' %}">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col-3 ">
              <div class="site-logo">
                <a href="../../webapp/templates/webapp/index.html">CarRent</a>
              </div>
            </div>

            <div class="col-9  text-right">


              <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>


              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href="{% url 'webapp:home' %}" class="nav-link">Home</a></li>
                  <li {% if request.resolver_match.url_name == 'services' %}class="active"{% endif %}><a href="{% url 'webapp:services' %}" class="nav-link">Services</a></li>
                  <li {% if request.resolver_match.url_name == 'cars' %}class="active"{% endif %}><a href="{% url 'webapp:cars' %}" class="nav-link">Cars</a></li>
                  <li {% if request.resolver_match.url_name == 'about' %}class="active"{% endif %}><a href="{% url 'webapp:about' %}" class="nav-link">About</a></li>
                  <li {% if request.resolver_match.url_name == 'blog' or request.resolver_match.url_name == 'single' %}class ="active"{% endif %}><a href="{% url 'blog:blog' %}" class="nav-link">Blog</a></li>
                  <li {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}><a href="{% url 'webapp:contact' %}" class="nav-link">Contact</a></li>
                </ul>
              </nav>
            </div>


          </div>
        </div>

      </header>

    {% block content %}{% endblock %}

    <!-- FOOTER -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <h2 class="footer-heading mb-4">About Us</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

    <script src= "{% static 'webapp/js/jquery-3.3.1.min.js' %}"></script>
    <script src= "{% static 'webapp/js/popper.min.js' %}"></script>
    <script src= "{% static 'webapp/js/bootstrap.min.js' %}"></script>
    <script src= "{% static 'webapp/js/owl.carousel.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.sticky.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.waypoints.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.animateNumber.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.fancybox.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.easing.1.3.js' %}"></script>
    <script src= "{% static 'webapp/js/bootstrap-datepicker.min.js' %}"></script>
    <script src= "{% static 'webapp/js/aos.js' %}"></script>

    <script src= "{% static 'webapp/js/main.js' %}"></script>

  </body>

</html>

webapp/templates/webapp/base.html
{% load static %}
<!doctype html>
<html lang="en">

  <head>
    <title>Car Rent &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href= "{% static 'webapp/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href= "{% static 'webapp/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href= "{% static 'webapp/css/aos.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href= "{% static 'webapp/css/style.css' %}">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col-3 ">
              <div class="site-logo">
                <a href="index.html">CarRent</a>
              </div>
            </div>

            <div class="col-9  text-right">


              <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>


              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href="{% url 'webapp:home' %}" class="nav-link">Home</a></li>
                  <li {% if request.resolver_match.url_name == 'services' %}class="active"{% endif %}><a href="services.html" class="nav-link">Services</a></li>
                  <li {% if request.resolver_match.url_name == 'cars' %}class="active"{% endif %}><a href="cars.html" class="nav-link">Cars</a></li>
                  <li {% if request.resolver_match.url_name == 'about' %}class="active"{% endif %}><a href="{% url 'webapp:about' %}" class="nav-link">About</a></li>
                  <li {% if request.resolver_match.url_name == 'blog' %}class ="active"{% endif %}><a href="blog.html" class="nav-link">Blog</a></li>
                  <li {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}><a href="contact.html" class="nav-link">Contact</a></li>
                </ul>
              </nav>
            </div>


          </div>
        </div>

      </header>

    {% block content %}{% endblock %}

    <!-- FOOTER -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <h2 class="footer-heading mb-4">About Us</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-3">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

    <script src= "{% static 'webapp/js/jquery-3.3.1.min.js' %}"></script>
    <script src= "{% static 'webapp/js/popper.min.js' %}"></script>
    <script src= "{% static 'webapp/js/bootstrap.min.js' %}"></script>
    <script src= "{% static 'webapp/js/owl.carousel.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.sticky.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.waypoints.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.animateNumber.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.fancybox.min.js' %}"></script>
    <script src= "{% static 'webapp/js/jquery.easing.1.3.js' %}"></script>
    <script src= "{% static 'webapp/js/bootstrap-datepicker.min.js' %}"></script>
    <script src= "{% static 'webapp/js/aos.js' %}"></script>

    <script src= "{% static 'webapp/js/main.js' %}"></script>

  </body>

</html>

webapp/templates/webapp/cars.html
{% extends 'main/base.html' %}
{% load static %}

    {% block content %}
    <div class="ftco-blocks-cover-1">
      <div class="ftco-cover-1 overlay innerpage" style="background-image: url('../../static/webapp/images/hero_2.jpg')">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-lg-6 text-center">
              <h1>Our For Rent Cars</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-light">
      <div class="container">
        <div class="row">

          {% for car in cars %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{{ car.photo.url }}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">{{ car.title }}</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>${{ car.price }}/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">{{ car.door_num }}</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">{{ car.seat_num }}</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">{{ car.transmission.title }}</span>
                    </li>
                    <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li>
                  </ul>
                  <div class="d-flex action">
                    <a href="contact.html" class="btn btn-primary">Rent Now</a>
                  </div>
                </div>
              </div>
          </div>
          {% endfor %}
          <div class="col-12">
            <span class="p-3">1</span>
            <a href="#" class="p-3">2</a>
            <a href="#" class="p-3">3</a>
            <a href="#" class="p-3">4</a>
          </div>
        </div>
      </div>
    </div>

    <div class="container site-section mb-5">
      <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
          <h2>How it works</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius earum voluptates sed!</p>
        </div>
      </div>
      <div class="how-it-works d-flex">
        <div class="step">
          <span class="number"><span>01</span></span>
          <span class="caption">Time &amp; Place</span>
        </div>
        <div class="step">
          <span class="number"><span>02</span></span>
          <span class="caption">Car</span>
        </div>
        <div class="step">
          <span class="number"><span>03</span></span>
          <span class="caption">Details</span>
        </div>
        <div class="step">
          <span class="number"><span>04</span></span>
          <span class="caption">Checkout</span>
        </div>
        <div class="step">
          <span class="number"><span>05</span></span>
          <span class="caption">Done</span>
        </div>

      </div>
    </div>

    {% endblock %}